spring.application.name=College-Alumni-Placement-Management-System
spring.datasource.url=jdbc:mysql://localhost:3306/alumni_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT secret (256-bit base64 encoded)
jwt.secret=your_super_long_and_complex_secret_key_for_atme_alumni_system_2025! # MUST BE AT LEAST 32 CHARACTERS
jwt.expiration=86400000
